title: eNATL60 with tides daily data
description: >-
  extractions of temperature, salinity and vertical velocity at 60m
  depth from eNATL60 NEMO simulation with explicit tides
recipes:
  - id: eNATL60_wtides_1d_tsw60m
    object: 'recipe:eNATL60_wtides_1d_tsw60m'
provenance:
  providers:
    - name: MEOM IGE
      description: >-
        Multiscale Ocean Modelling Group, Institut des Geosciences de
        l'Environnement, Grenoble, France
      roles:
        - producer
        - licensor
      url: 'http://meom-group.github.io/'
  license: CC-BY-4.0
maintainers:
  - name: Aurélie Albert
    orcid: 0000-0001-7783-5629
    github: auraoupa
bakery:
  id: pangeo-ldeo-nsf-earthcube
